### ISSUE TITLE
[REQ] 1.9 Support

### ISSUE THREAD

**Issue by Fabricio20** [Virizion/Corpses#2]
Hello, do you plan to update this to Minecraft 1.9?

**Comment by s-k-y-l-i** [comment]
please please please

**Comment by portlek** [comment]
👯 check code and rewite own nms class .-.

**Comment by egold555** [comment]
I am now the maintainer of the plugin. I have updated it to support 1.8-1.10.2

https://www.spigotmc.org/resources/corpsereborn.29875/
